# Generated by Django 5.1.5 on 2025-01-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=120, verbose_name='نام قروشگاه')),
                ('logo', models.ImageField(upload_to='Media/logo', verbose_name='لوگو')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('address', models.CharField(max_length=300, verbose_name='آدرس فروشگاه')),
                ('about_us_title', models.CharField(max_length=200, verbose_name='تیتر درباره ما')),
                ('about_us_text', models.TextField(verbose_name='متن درباره ما')),
                ('copy_right_text', models.TextField(verbose_name='متن کپی رایت')),
                ('whatsapp_link', models.URLField(verbose_name='لینک واتساپ')),
                ('telegram_link', models.URLField(verbose_name='لینک تلگرام')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
