# Generated by Django 5.1.5 on 2025-01-30 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterHeaderTableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=40, verbose_name='نام دسته بندی فوتر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
            ],
            options={
                'verbose_name': 'دسته بندی فوتر',
                'verbose_name_plural': 'دسته بندی های فوتر',
            },
        ),
        migrations.CreateModel(
            name='FooterLinksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='نام لینک')),
                ('link', models.URLField(verbose_name='لینک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeModule.footerheadertablemodel', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'لینک فوتر',
                'verbose_name_plural': 'لینک های فوتر',
            },
        ),
    ]
