# Generated by Django 5.1.5 on 2025-01-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeModule', '0002_footerheadertablemodel_footerlinksmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerlinksmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='sitesettingsmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.DeleteModel(
            name='FooterHeaderTableModel',
        ),
        migrations.DeleteModel(
            name='FooterLinksModel',
        ),
    ]
