# Generated by Django 5.1.5 on 2025-01-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeModule', '0005_slidermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicklinkmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیر فعال'),
        ),
        migrations.AddField(
            model_name='sitesettingsmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیر فعال'),
        ),
        migrations.AddField(
            model_name='slidermodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیر فعال'),
        ),
    ]
