# Generated by Django 5.1.5 on 2025-01-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeModule', '0006_quicklinkmodel_is_active_sitesettingsmodel_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingsmodel',
            name='contact_us_text',
            field=models.TextField(null=True, verbose_name='متن تماس با ما'),
        ),
    ]
