# Generated by Django 5.1.5 on 2025-01-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeModule', '0007_sitesettingsmodel_contact_us_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettingsmodel',
            name='telegram_link',
        ),
        migrations.RemoveField(
            model_name='sitesettingsmodel',
            name='whatsapp_link',
        ),
        migrations.AddField(
            model_name='sitesettingsmodel',
            name='telegram_phone_number',
            field=models.URLField(null=True, verbose_name='شماره تلگرام'),
        ),
        migrations.AddField(
            model_name='sitesettingsmodel',
            name='whatsapp_phone_number',
            field=models.URLField(null=True, verbose_name='شماره واتساپ'),
        ),
    ]
