# Generated by Django 5.1.5 on 2025-02-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeModule', '0008_remove_sitesettingsmodel_telegram_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettingsmodel',
            name='telegram_phone_number',
        ),
        migrations.RemoveField(
            model_name='sitesettingsmodel',
            name='whatsapp_phone_number',
        ),
        migrations.AddField(
            model_name='sitesettingsmodel',
            name='instagram',
            field=models.URLField(null=True, verbose_name='اینستاگرم'),
        ),
        migrations.AddField(
            model_name='sitesettingsmodel',
            name='telegram',
            field=models.URLField(null=True, verbose_name='تلگرام'),
        ),
        migrations.AddField(
            model_name='sitesettingsmodel',
            name='whatsapp',
            field=models.URLField(null=True, verbose_name='واتساپ'),
        ),
    ]
