# Generated by Django 5.1.5 on 2025-02-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeModule', '0009_remove_sitesettingsmodel_telegram_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingsmodel',
            name='second_phone_number',
            field=models.CharField(max_length=20, null=True, verbose_name='شماره تماس'),
        ),
    ]
