# Generated by Django 5.1.5 on 2025-01-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='سر تیتر')),
                ('text', models.TextField(verbose_name='متن')),
                ('image', models.ImageField(upload_to='Media/Tutorial-images', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
            ],
            options={
                'verbose_name': 'آموزش',
                'verbose_name_plural': 'آموزش\u200cهای',
            },
        ),
    ]
