# Generated by Django 5.1.5 on 2025-01-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorialModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorialmodel',
            options={'verbose_name': 'آموزش', 'verbose_name_plural': 'آموزش\u200cها'},
        ),
        migrations.AddField(
            model_name='tutorialmodel',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tutorialmodel',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='سر تیتر'),
        ),
    ]
