# Generated by Django 5.1.5 on 2025-01-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorialModule', '0003_remove_tutorialmodel_slug_remove_tutorialmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tutorialmodel',
            name='title',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='سر تیتر'),
        ),
    ]
