# Generated by Django 5.1.5 on 2025-01-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorialModule', '0004_tutorialmodel_slug_tutorialmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialmodel',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
