# Generated by Django 5.1.5 on 2025-01-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorialModule', '0006_alter_tutorialmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorialmodel',
            name='writer',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='نویسنده'),
        ),
    ]
