# Generated by Django 5.1.5 on 2025-01-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorialModule', '0007_tutorialmodel_created_at_tutorialmodel_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialmodel',
            name='writer',
            field=models.CharField(max_length=200, null=True, verbose_name='نویسنده'),
        ),
    ]
