# Generated by Django 5.1.5 on 2025-01-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorialModule', '0011_tutorialmodel_show_on_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialmodel',
            name='minutes_to_read',
            field=models.IntegerField(default=5, verbose_name='چند دقیقه برای مطالعه نیاز است ؟'),
        ),
    ]
