# Generated by Django 5.1.5 on 2025-02-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorialModule', '0012_tutorialmodel_minutes_to_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialmodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False, null=True),
        ),
    ]
