# Generated by Django 5.1.5 on 2025-01-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ماشین')),
                ('image', models.ImageField(upload_to='Media/CarImages', verbose_name='تصویر ماشین')),
            ],
            options={
                'verbose_name': 'ماشین',
                'verbose_name_plural': 'ماشین ها',
            },
        ),
    ]
