# Generated by Django 5.1.5 on 2025-01-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarModule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیر فعال'),
        ),
    ]
