# Generated by Django 5.1.5 on 2025-01-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarModule', '0002_carmodel_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'خودرو', 'verbose_name_plural': 'خودروها'},
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='image',
            field=models.ImageField(upload_to='Media/CarImages', verbose_name='تصویر خودرو'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='خودرو'),
        ),
    ]
