# Generated by Django 5.1.5 on 2025-01-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarModule', '0003_alter_carmodel_options_alter_carmodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='show_on_main',
            field=models.BooleanField(default=False, verbose_name='نشان دادن در خانه'),
        ),
    ]
