# Generated by Django 5.1.5 on 2025-01-31 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarModule', '0004_carmodel_show_on_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
