# Generated by Django 5.1.5 on 2025-01-31 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarModule', '0005_carmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='خودرو'),
        ),
    ]
