# Generated by Django 5.1.5 on 2025-01-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='main_image',
            field=models.ImageField(null=True, upload_to='Media/product-images', verbose_name='تصویر محصول'),
        ),
    ]
