# Generated by Django 5.1.5 on 2025-01-31 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductModule', '0003_productmodel_cod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='main_image',
            new_name='image',
        ),
    ]
