# Generated by Django 5.1.5 on 2025-01-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductModule', '0004_rename_main_image_productmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='country',
            field=models.CharField(max_length=54, null=True, verbose_name='کشور'),
        ),
    ]
