# Generated by Django 5.1.5 on 2025-01-31 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductModule', '0005_productmodel_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='brand',
            field=models.CharField(max_length=54, null=True, unique=True, verbose_name='برند'),
        ),
    ]
